server:
  port: 8083

spring:
  application:
    name: new-gateways

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
      instance:
      preferIpAddress: true

zuul:
  routes:
    ORDER-MANAGEMENT:
      path: /oms/**
      url: http://localhost:8081
      customSensitiveHeaders: true